/// Flutter icons CustomIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';

  static const IconData avatar = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData otp_icon = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData lock = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData mail_icon = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData mobile_icon = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData home = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData inventory = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData egg = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData food__1_ = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData food = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData group_3661 = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData ketogenic_diet = IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData milk = IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData peanut = IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData sesame = IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData shrimp = IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData soybean = IconData(0xe810, fontFamily: _kFontFam);
  static const IconData soy_free = IconData(0xe811, fontFamily: _kFontFam);
  static const IconData wheat__1_ = IconData(0xe812, fontFamily: _kFontFam);
  static const IconData wheat = IconData(0xe813, fontFamily: _kFontFam);
  static const IconData chicken = IconData(0xe814, fontFamily: _kFontFam);
  static const IconData dairy_product = IconData(0xe815, fontFamily: _kFontFam);
  static const IconData dolly_fish = IconData(0xe816, fontFamily: _kFontFam);
}
